'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Sparkles, RefreshCw, Loader2, MessageCircle } from 'lucide-react'
import { useTheme } from '@/hooks/useTheme'
import { cn } from '@/lib/utils'
import { motion, AnimatePresence } from 'framer-motion'
import DOMPurify from 'isomorphic-dompurify'
import { formatAnalysis, formatAnalysisSections } from './formatters'
import { getAnalysisConfig } from './ai-analysis.config'
import type { PageType, DateRange, AnalysisResponse, AnalysisData } from './types'

interface AIAnalysisCardProps {
  pageType: PageType
  data: any
  dateRange: DateRange
  context?: Record<string, any>
  autoGenerate?: boolean
  dataLoadingStates?: Record<string, boolean>
  onAnalysisItemClick?: (text: string, sectionType: 'strategic' | 'forward' | 'actions') => void
  /** 'card' (default) wraps in a glass-luxury-card; 'section' renders borderless to match BC dashboard sections */
  variant?: 'card' | 'section'
  className?: string
}

export function AIAnalysisCard({
  pageType,
  data,
  dateRange,
  context = {},
  autoGenerate = true,
  dataLoadingStates,
  onAnalysisItemClick,
  className,
  variant = 'card',
}: AIAnalysisCardProps) {
  const config = getAnalysisConfig(pageType)
  const { theme } = useTheme()
  const isLight = theme === 'light'

  const [analysis, setAnalysis] = useState<AnalysisData | string | null>(null)
  const [loading, setLoading] = useState(false)
  const [hasGenerated, setHasGenerated] = useState(false)
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null)
  const [relativeTime, setRelativeTime] = useState<string>('')
  const [remainingCooldown, setRemainingCooldown] = useState(0)
  const [popup, setPopup] = useState<{
    show: boolean
    x: number
    y: number
    scrollY: number
    itemText: string
    sectionType: 'strategic' | 'forward' | 'actions'
  } | null>(null)

  const contentRef = useRef<HTMLDivElement>(null)
  const hasAutoGeneratedRef = useRef(false)
  const dateRangeRef = useRef<string>('')

  // Calculate remaining cooldown based on lastUpdated timestamp
  useEffect(() => {
    if (!lastUpdated) {
      setRemainingCooldown(0)
      return
    }

    const updateCooldown = () => {
      const now = new Date()
      const diffMs = now.getTime() - lastUpdated.getTime()
      const diffSeconds = Math.floor(diffMs / 1000)
      const remaining = Math.max(0, 30 - diffSeconds)
      setRemainingCooldown(remaining)
    }

    updateCooldown()
    const timer = setInterval(updateCooldown, 1000)

    return () => clearInterval(timer)
  }, [lastUpdated])

  // Update relative time
  useEffect(() => {
    if (!lastUpdated) return

    const updateRelativeTime = () => {
      const now = new Date()
      const diffMs = now.getTime() - lastUpdated.getTime()
      const diffMins = Math.floor(diffMs / 60000)

      if (diffMins < 1) {
        setRelativeTime('just now')
      } else if (diffMins === 1) {
        setRelativeTime('1 minute ago')
      } else {
        setRelativeTime(`${diffMins} minutes ago`)
      }
    }

    updateRelativeTime()
    const interval = setInterval(updateRelativeTime, 30000) // Update every 30 seconds

    return () => clearInterval(interval)
  }, [lastUpdated])

  // Check if data is complete for generation
  const isDataComplete = useCallback(() => {
    if (!data || !dateRange?.start || !dateRange?.end) return false
    return true
  }, [data, dateRange])

  // Handle clicking on analysis items to send to chat
  const handleAnalysisItemClick = useCallback(
    (itemText: string, sectionType: 'strategic' | 'forward' | 'actions') => {
      if (onAnalysisItemClick) {
        onAnalysisItemClick(itemText, sectionType)
        return
      }

      // Default behavior: dispatch custom event for chat integration
      const contextPrompt = `Based on this AI analysis insight from the ${config.displayName}:\n\n"${itemText}"\n\nPlease provide more details and actionable recommendations.`

      window.dispatchEvent(
        new CustomEvent('chat-send-message', {
          detail: { message: contextPrompt, openChat: true },
        })
      )
    },
    [onAnalysisItemClick, config.displayName]
  )

  // Generate analysis
  const generateAnalysis = async (forceRegenerate: boolean = false) => {
    if (loading) return
    if (!isDataComplete()) {
      return
    }

    setLoading(true)

    try {
      const response = await fetch(`/api/analysis/${pageType}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          data,
          dateRange,
          context,
          forceRegenerate,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        const errorMessage = errorData.message || errorData.error || 'Unknown error'

        if (response.status === 503) {
          throw new Error(`AI service temporarily unavailable: ${errorMessage}`)
        } else if (response.status === 429) {
          throw new Error('Rate limit exceeded. Please wait before trying again.')
        } else {
          throw new Error(`Server error: ${errorMessage}`)
        }
      }

      const result: AnalysisResponse = await response.json()
      setAnalysis(result.analysis)
      setHasGenerated(true)
      setLastUpdated(new Date(result.createdAt))

      if (forceRegenerate) {
        console.log(`[AI Analysis - ${pageType}] Forced regeneration completed`)
      } else if (result.cached) {
        console.log(`[AI Analysis - ${pageType}] Loaded from cache`)
      }

      if (result.validation) {
        console.log(`[AI Analysis - ${pageType}] Validation:`, result.validation)
      }
    } catch (error: any) {
      const errorMessage = error?.message || 'Unknown error occurred'
      console.error(`Failed to generate ${pageType} analysis:`, error)

      if (errorMessage.includes('temporarily unavailable') || errorMessage.includes('503')) {
        setAnalysis(
          'The AI analysis service is temporarily unavailable.\n\nPlease try again in a few moments.'
        )
      } else if (errorMessage.includes('Rate limit') || errorMessage.includes('429')) {
        setAnalysis('Rate limit exceeded.\n\nPlease wait 30 seconds before trying again.')
      } else {
        setAnalysis(
          `Failed to generate analysis: ${errorMessage}\n\nPlease try again or contact support.`
        )
      }
    } finally {
      setLoading(false)
    }
  }

  // Set up event delegation for clickable analysis items
  useEffect(() => {
    const container = contentRef.current
    if (!container) return

    const handleClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement
      const clickableItem = target.closest('[data-analysis-item]')

      if (clickableItem) {
        event.preventDefault()
        event.stopPropagation()

        const itemText = clickableItem.getAttribute('data-item-text')
        const sectionType = clickableItem.getAttribute('data-section-type') as
          | 'strategic'
          | 'forward'
          | 'actions'

        if (itemText && sectionType) {
          // Position at cursor, store scroll position so popup stays in place when scrolling
          setPopup({
            show: true,
            x: event.clientX,
            y: event.clientY,
            scrollY: window.scrollY,
            itemText,
            sectionType,
          })
        }
      }
    }

    container.addEventListener('click', handleClick)
    return () => container.removeEventListener('click', handleClick)
  }, [analysis])

  // Auto-generate analysis when all data is loaded
  useEffect(() => {
    if (!autoGenerate) return

    // Check if all data is loaded
    const allDataLoaded =
      !dataLoadingStates || Object.values(dataLoadingStates).every((loading) => !loading)

    // Create unique key for date range
    const currentDateRangeKey = `${dateRange?.start}_${dateRange?.end}`
    const isNewDateRange = dateRangeRef.current !== currentDateRangeKey

    // Auto-generate if:
    // 1. All data loaded
    // 2. Data is complete
    // 3. Either never auto-generated OR date range changed
    // 4. Not currently loading
    if (
      allDataLoaded &&
      isDataComplete() &&
      ((!hasAutoGeneratedRef.current && !hasGenerated) || isNewDateRange) &&
      !loading
    ) {
      console.log(`[AI Analysis - ${pageType}] Auto-generating`, {
        allDataLoaded,
        isNewDateRange,
        currentDateRangeKey,
      })

      // Update refs
      hasAutoGeneratedRef.current = true
      dateRangeRef.current = currentDateRangeKey

      // Generate with slight delay to ensure UI is ready
      setTimeout(() => generateAnalysis(false), 100)
    }
  }, [autoGenerate, dataLoadingStates, dateRange, isDataComplete, loading, hasGenerated, pageType])

  const refreshButton = (
    <Button
      onClick={() => generateAnalysis(hasGenerated)}
      disabled={loading || remainingCooldown > 0 || !isDataComplete()}
      size="sm"
      variant="ghost"
      className="h-8 px-3 text-xs font-medium theme-text-primary hover:bg-amber-500/10 border border-amber-500/20 hover:border-amber-500/30"
    >
      {loading ? (
        <>
          <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
          <span className="hidden sm:inline">Analyzing...</span>
        </>
      ) : remainingCooldown > 0 ? (
        <>
          <span className="hidden sm:inline">Wait {remainingCooldown}s</span>
          <span className="sm:hidden">{remainingCooldown}s</span>
        </>
      ) : hasGenerated ? (
        <>
          <RefreshCw className="mr-1.5 h-3.5 w-3.5" />
          <span className="hidden sm:inline">Refresh</span>
        </>
      ) : (
        <>
          <Sparkles className="mr-1.5 h-3.5 w-3.5" />
          <span className="hidden sm:inline">Generate</span>
        </>
      )}
    </Button>
  )

  const sanitizeOpts = {
    ADD_ATTR: ['data-analysis-item', 'data-item-text', 'data-section-type', 'title'],
    ADD_TAGS: ['svg', 'path', 'strong'],
    ALLOW_DATA_ATTR: true,
  }

  // Check if analysis is valid structured data
  const isStructured =
    analysis &&
    !loading &&
    typeof analysis !== 'string' &&
    analysis.strategicInsights &&
    analysis.forwardLooking &&
    analysis.prioritizedActions

  // Data is still loading (pre-analysis)
  const isDataLoading =
    autoGenerate && dataLoadingStates && Object.values(dataLoadingStates).some((l) => l)

  const analysisContent = (
    <div ref={contentRef}>
      <AnimatePresence mode="wait">
        {!hasGenerated && !loading && !isDataLoading && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="flex flex-col items-center justify-center py-12 text-center"
          >
            <div className="p-4">
              <Sparkles className="w-10 h-10 text-amber-500/40" />
            </div>
            <h3 className="text-base font-semibold theme-text-primary mb-2">Ready to Analyze</h3>
            <p className="text-sm theme-text-secondary max-w-md">
              Click &ldquo;Generate Analysis&rdquo; to get AI-powered insights
            </p>
          </motion.div>
        )}

        {(loading || isDataLoading) && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-12"
          >
            <div className="p-4">
              <Loader2 className="w-8 h-8 animate-spin text-amber-500" />
            </div>
            <p className="text-sm font-medium theme-text-primary mb-1">Analyzing Data</p>
            <p className="text-xs theme-text-secondary">Generating insights...</p>
          </motion.div>
        )}

        {analysis && !loading && !isStructured && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
          >
            <div className="text-sm leading-relaxed theme-text-primary whitespace-pre-wrap">
              {typeof analysis === 'string' ? analysis : JSON.stringify(analysis, null, 2)}
            </div>
          </motion.div>
        )}

        {isStructured && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="ai-analysis-content"
          >
            <div
              className="text-sm leading-relaxed space-y-3 theme-text-primary"
              dangerouslySetInnerHTML={{
                __html: DOMPurify.sanitize(formatAnalysis(analysis), sanitizeOpts),
              }}
            />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )

  const popupElement = popup?.show ? (
    <AskMidasPopup popup={popup} onClose={() => setPopup(null)} onAsk={handleAnalysisItemClick} />
  ) : null

  if (variant === 'section') {
    const sections = isStructured ? formatAnalysisSections(analysis) : null

    const sectionItems = sections
      ? [
          { key: 'strategic', html: sections.strategic },
          { key: 'forward', html: sections.forward },
          { key: 'actions', html: sections.actions },
        ]
      : []

    const borderClass = isLight ? 'border-stone-200' : 'border-white/[0.08]'
    const sectionHoverClass = cn(
      'group relative -mx-3 px-3 -mt-4 pt-4 -mb-6 pb-6 rounded-[4px]',
      'transition-all duration-300 ease-out',
      'hover:scale-[1.02] origin-center',
      isLight
        ? 'hover:shadow-[0_4px_20px_-4px_rgba(0,0,0,0.1)]'
        : 'hover:shadow-[0_4px_20px_-4px_rgba(0,0,0,0.4)]'
    )

    return (
      <div ref={!sections ? contentRef : undefined} className={className}>
        {/* Refresh button row — no title header */}
        <div className="flex items-center justify-end gap-2 mb-4">
          {relativeTime && <span className="text-xs theme-text-secondary">{relativeTime}</span>}
          {refreshButton}
        </div>

        {/* Pre-analysis: loading skeleton */}
        {!sections && (loading || isDataLoading) && (
          <div>
            {/* Strategic Insights skeleton — full width */}
            <section className={sectionHoverClass}>
              <div className="text-sm leading-relaxed">
                <div
                  className={cn(
                    'h-5 w-40 mb-6 animate-pulse',
                    isLight ? 'bg-stone-200' : 'bg-white/[0.06]'
                  )}
                />
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 0 }}>
                  {[85, 65, 90, 55, 75, 80].map((w, i) => (
                    <div key={i} className="flex gap-3 py-2.5 px-3">
                      <span
                        className={cn(
                          'text-[10px] flex-shrink-0 mt-[5px]',
                          isLight ? 'text-blue-300' : 'text-blue-500/30'
                        )}
                      >
                        &#9670;
                      </span>
                      <div className="flex-1 space-y-1.5">
                        <div
                          className={cn(
                            'h-3.5 animate-pulse',
                            isLight ? 'bg-stone-200' : 'bg-white/[0.06]'
                          )}
                        />
                        <div
                          className={cn(
                            'h-3.5 animate-pulse',
                            isLight ? 'bg-stone-200' : 'bg-white/[0.06]'
                          )}
                          style={{ width: `${w}%` }}
                        />
                        <div
                          className={cn(
                            'h-3.5 animate-pulse',
                            isLight ? 'bg-stone-200' : 'bg-white/[0.06]'
                          )}
                          style={{ width: `${w - 25}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Forward + Actions skeleton — 2 columns */}
            <div className={cn('grid grid-cols-1 @3xl:grid-cols-2 gap-x-12 gap-y-20 mt-12')}>
              <section
                className={cn(
                  'flex flex-col',
                  '@3xl:pr-8 relative @3xl:after:absolute @3xl:after:right-0 @3xl:after:top-4 @3xl:after:bottom-4 @3xl:after:w-px',
                  isLight ? '@3xl:after:bg-stone-200' : '@3xl:after:bg-white/[0.08]',
                  sectionHoverClass
                )}
              >
                <div className="text-sm leading-relaxed">
                  <div className={cn('h-5 w-52 mb-6 animate-pulse', isLight ? 'bg-stone-200' : 'bg-white/[0.06]')} />
                  {[90, 70, 85].map((w, i) => (
                    <div key={i} className="flex gap-3 py-2.5 px-3 -mx-3">
                      <span className={cn('text-xs flex-shrink-0 mt-[3px]', isLight ? 'text-purple-300' : 'text-purple-500/30')}>&#8594;</span>
                      <div className="flex-1 space-y-1.5">
                        <div className={cn('h-3.5 animate-pulse', isLight ? 'bg-stone-200' : 'bg-white/[0.06]')} />
                        <div className={cn('h-3.5 animate-pulse', isLight ? 'bg-stone-200' : 'bg-white/[0.06]')} style={{ width: `${w}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </section>
              <section className={cn('flex flex-col', sectionHoverClass)}>
                <div className="text-sm leading-relaxed">
                  <div className={cn('h-5 w-44 mb-6 animate-pulse', isLight ? 'bg-stone-200' : 'bg-white/[0.06]')} />
                  {[80, 65, 90].map((w, i) => (
                    <div key={i} className="flex gap-3 py-2.5 px-3 -mx-3">
                      <span className={cn('flex-shrink-0 w-[18px] h-[18px] rounded-full text-[10px] font-semibold flex items-center justify-center mt-[2px]', isLight ? 'text-blue-300 border border-blue-300' : 'text-blue-500/30 border border-blue-500/30')}>{i + 1}</span>
                      <div className="flex-1 space-y-1.5">
                        <div className={cn('h-3.5 animate-pulse', isLight ? 'bg-blue-100' : 'bg-blue-500/10')} style={{ width: '60%' }} />
                        <div className={cn('h-3.5 animate-pulse', isLight ? 'bg-stone-200' : 'bg-white/[0.06]')} style={{ width: `${w}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            </div>
          </div>
        )}

        {/* Pre-analysis: ready / non-loading states */}
        {!sections && !loading && !isDataLoading && analysisContent}

        {/* Strategic Insights — full width */}
        {sections && sectionItems[0]?.html && (
          <div ref={contentRef}>
            <section className={sectionHoverClass}>
              <div
                className="text-sm leading-relaxed theme-text-primary"
                dangerouslySetInnerHTML={{
                  __html: DOMPurify.sanitize(sectionItems[0].html, sanitizeOpts),
                }}
              />
            </section>

            {/* Forward Analysis + Prioritized Actions — 2 columns */}
            {(sectionItems[1]?.html || sectionItems[2]?.html) && (
              <div className={cn('grid grid-cols-1 @3xl:grid-cols-2 gap-x-12 gap-y-20 mt-12')}>
                {sectionItems.slice(1).map((section, i) => (
                  <section
                    key={section.key}
                    className={cn(
                      'flex flex-col',
                      i === 0 &&
                        '@3xl:pr-8 relative @3xl:after:absolute @3xl:after:right-0 @3xl:after:top-4 @3xl:after:bottom-4 @3xl:after:w-px',
                      i === 0 && (isLight ? '@3xl:after:bg-stone-200' : '@3xl:after:bg-white/[0.08]'),
                      sectionHoverClass
                    )}
                  >
                    <div
                      className="text-sm leading-relaxed theme-text-primary"
                      dangerouslySetInnerHTML={{
                        __html: DOMPurify.sanitize(section.html, sanitizeOpts),
                      }}
                    />
                  </section>
                ))}
              </div>
            )}
          </div>
        )}

        {popupElement}
      </div>
    )
  }

  return (
    <Card className="glass-luxury-card border border-gray-200/10 flex flex-col gap-0">
      <CardHeader className="px-6 pb-3">
        <CardTitle className="flex items-center justify-between w-full theme-text-primary text-base">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span className="font-bold">{config.displayName}</span>
            {relativeTime && (
              <span className="text-xs font-normal theme-text-secondary ml-1">{relativeTime}</span>
            )}
          </div>
          {refreshButton}
        </CardTitle>
      </CardHeader>

      <CardContent className="px-6 pb-4 pt-0">{analysisContent}</CardContent>

      {popupElement}
    </Card>
  )
}

// Popup component rendered via portal
function AskMidasPopup({
  popup,
  onClose,
  onAsk,
}: {
  popup: {
    show: boolean
    x: number
    y: number
    scrollY: number
    itemText: string
    sectionType: 'strategic' | 'forward' | 'actions'
  }
  onClose: () => void
  onAsk: (itemText: string, sectionType: 'strategic' | 'forward' | 'actions') => void
}) {
  const [currentScrollY, setCurrentScrollY] = useState(window.scrollY)

  // Track scroll to adjust popup position
  useEffect(() => {
    const handleScroll = () => setCurrentScrollY(window.scrollY)
    window.addEventListener('scroll', handleScroll, { passive: true })
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  // Close popup when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as HTMLElement
      if (!target.closest('.ask-midas-popup')) {
        onClose()
      }
    }

    setTimeout(() => {
      document.addEventListener('click', handleClickOutside)
    }, 10)

    return () => document.removeEventListener('click', handleClickOutside)
  }, [onClose])

  // Calculate position: original viewport position adjusted for scroll difference
  const scrollDiff = currentScrollY - popup.scrollY
  const top = popup.y - scrollDiff

  return createPortal(
    <AnimatePresence>
      {popup.show && (
        <motion.div
          initial={{ opacity: 0, y: 4, scale: 0.96 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 2, scale: 0.98 }}
          transition={{ duration: 0.12, ease: [0.23, 1, 0.32, 1] }}
          className="ask-midas-popup fixed z-[9999]"
          style={{
            left: `${popup.x}px`,
            top: `${top + 8}px`,
          }}
        >
          <button
            onClick={(e) => {
              e.stopPropagation()
              onAsk(popup.itemText, popup.sectionType)
              onClose()
            }}
            className="backdrop-blur-xl bg-amber-500/90 hover:bg-amber-500 text-white text-[11px] font-medium tracking-wide px-3.5 py-1.5 rounded-full shadow-[0_2px_12px_-2px_rgba(245,158,11,0.4)] flex items-center gap-1.5 transition-all duration-150 hover:shadow-[0_4px_16px_-2px_rgba(245,158,11,0.5)]"
          >
            <MessageCircle className="w-3 h-3" />
            <span>Ask Midas</span>
          </button>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  )
}
