'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import { getAnalysisConfig } from './ai-analysis.config'
import type { PageType, DateRange, AnalysisResponse, AnalysisData } from './types'

interface UseAIAnalysisOptions {
  pageType: PageType
  data: any
  dateRange: DateRange
  context?: Record<string, any>
  autoGenerate?: boolean
  dataLoadingStates?: Record<string, boolean>
}

export function useAIAnalysis({
  pageType,
  data,
  dateRange,
  context = {},
  autoGenerate = true,
  dataLoadingStates,
}: UseAIAnalysisOptions) {
  const config = getAnalysisConfig(pageType)

  const [analysis, setAnalysis] = useState<AnalysisData | string | null>(null)
  const [loading, setLoading] = useState(false)
  const [hasGenerated, setHasGenerated] = useState(false)
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null)
  const [relativeTime, setRelativeTime] = useState<string>('')
  const [remainingCooldown, setRemainingCooldown] = useState(0)

  const hasAutoGeneratedRef = useRef(false)
  const dateRangeRef = useRef<string>('')

  // Calculate remaining cooldown based on lastUpdated timestamp
  useEffect(() => {
    if (!lastUpdated) {
      setRemainingCooldown(0)
      return
    }

    const updateCooldown = () => {
      const now = new Date()
      const diffMs = now.getTime() - lastUpdated.getTime()
      const diffSeconds = Math.floor(diffMs / 1000)
      const remaining = Math.max(0, 30 - diffSeconds)
      setRemainingCooldown(remaining)
    }

    updateCooldown()
    const timer = setInterval(updateCooldown, 1000)

    return () => clearInterval(timer)
  }, [lastUpdated])

  // Update relative time
  useEffect(() => {
    if (!lastUpdated) return

    const updateRelativeTime = () => {
      const now = new Date()
      const diffMs = now.getTime() - lastUpdated.getTime()
      const diffMins = Math.floor(diffMs / 60000)

      if (diffMins < 1) {
        setRelativeTime('just now')
      } else if (diffMins === 1) {
        setRelativeTime('1 minute ago')
      } else {
        setRelativeTime(`${diffMins} minutes ago`)
      }
    }

    updateRelativeTime()
    const interval = setInterval(updateRelativeTime, 30000)

    return () => clearInterval(interval)
  }, [lastUpdated])

  // Check if data is complete for generation
  const isDataComplete = useCallback(() => {
    if (!data || !dateRange?.start || !dateRange?.end) return false
    return true
  }, [data, dateRange])

  // Generate analysis
  const generateAnalysis = useCallback(
    async (forceRegenerate: boolean = false) => {
      if (loading) return
      if (!isDataComplete()) return

      setLoading(true)

      try {
        const response = await fetch(`/api/analysis/${pageType}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            data,
            dateRange,
            context,
            forceRegenerate,
          }),
        })

        if (!response.ok) {
          const errorData = await response.json().catch(() => ({}))
          const errorMessage = errorData.message || errorData.error || 'Unknown error'

          if (response.status === 503) {
            throw new Error(`AI service temporarily unavailable: ${errorMessage}`)
          } else if (response.status === 429) {
            throw new Error('Rate limit exceeded. Please wait before trying again.')
          } else {
            throw new Error(`Server error: ${errorMessage}`)
          }
        }

        const result: AnalysisResponse = await response.json()
        setAnalysis(result.analysis)
        setHasGenerated(true)
        setLastUpdated(new Date(result.createdAt))

        if (forceRegenerate) {
          console.log(`[AI Analysis - ${pageType}] Forced regeneration completed`)
        } else if (result.cached) {
          console.log(`[AI Analysis - ${pageType}] Loaded from cache`)
        }
      } catch (error: any) {
        const errorMessage = error?.message || 'Unknown error occurred'
        console.error(`Failed to generate ${pageType} analysis:`, error)

        if (errorMessage.includes('temporarily unavailable') || errorMessage.includes('503')) {
          setAnalysis(
            'The AI analysis service is temporarily unavailable.\n\nPlease try again in a few moments.'
          )
        } else if (errorMessage.includes('Rate limit') || errorMessage.includes('429')) {
          setAnalysis('Rate limit exceeded.\n\nPlease wait 30 seconds before trying again.')
        } else {
          setAnalysis(
            `Failed to generate analysis: ${errorMessage}\n\nPlease try again or contact support.`
          )
        }
      } finally {
        setLoading(false)
      }
    },
    [loading, isDataComplete, pageType, data, dateRange, context]
  )

  // Reset analysis immediately when date range changes so shimmer shows right away
  useEffect(() => {
    const currentDateRangeKey = `${dateRange?.start}_${dateRange?.end}`
    if (dateRangeRef.current && dateRangeRef.current !== currentDateRangeKey) {
      setAnalysis(null)
      setHasGenerated(false)
    }
  }, [dateRange])

  // Auto-generate analysis when all data is loaded
  useEffect(() => {
    if (!autoGenerate) return

    const allDataLoaded =
      !dataLoadingStates || Object.values(dataLoadingStates).every((loading) => !loading)

    const currentDateRangeKey = `${dateRange?.start}_${dateRange?.end}`
    const isNewDateRange = dateRangeRef.current !== currentDateRangeKey

    if (
      allDataLoaded &&
      isDataComplete() &&
      ((!hasAutoGeneratedRef.current && !hasGenerated) || isNewDateRange) &&
      !loading
    ) {
      hasAutoGeneratedRef.current = true
      dateRangeRef.current = currentDateRangeKey

      setTimeout(() => generateAnalysis(false), 100)
    }
  }, [autoGenerate, dataLoadingStates, dateRange, isDataComplete, loading, hasGenerated, pageType])

  const isStructured =
    analysis &&
    typeof analysis !== 'string' &&
    analysis.strategicInsights &&
    analysis.forwardLooking &&
    analysis.prioritizedActions

  return {
    analysis,
    loading,
    hasGenerated,
    relativeTime,
    remainingCooldown,
    isDataComplete,
    generateAnalysis,
    isStructured: !!isStructured,
    structuredAnalysis: isStructured ? (analysis as AnalysisData) : null,
    config,
  }
}
